x-server-env: &server-env
  APP_GATEWAY_HOST: 0.0.0.0
  APP_GATEWAY_PORT: 4001
  API_GATEWAY_HOST: api-gateway
  API_GATEWAY_PORT: 4000
  API_GATEWAY_PORT_2: 4002
  USER_SERVICE_HOST: user-service
  USER_SERVICE_PORT: 4003
  USER_SERVICE_REDIS_HOST: redis
  USER_SERVICE_REDIS_PORT: 6379
  CLIENT_URL: http://a7a29bab3405841518b42d403a6ace1b-1831602282.ap-south-1.elb.amazonaws.com
  ALLOWED_ORIGINS: http://localhost:3002
  MONGO_URI: mongodb://root:example@mongodb:27017/

services:
  # ─── MongoDB ───
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  # ─── Mongo-Express ───
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - app-network

  # ─── Redis ───
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  # ─── User Service ───
  user-service:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
      args:
        SERVICE: user-service
        PORT: 4003
    environment:
      <<: *server-env
      SERVICE: user-service
    ports:
      - "4003:4003"
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network
  
  # ─── App Gateway ───
  app-gateway:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
      args:
        SERVICE: app-gateway
        PORT: 4001
    environment:
      <<: *server-env
      SERVICE: app-gateway
    ports:
      - "4001:4001"
    depends_on:
      - user-service
    networks:
      - app-network

  # ─── API Gateway ───
  api-gateway:
    build:
      context: ./packages/server
      dockerfile: Dockerfile
      args:
        SERVICE: api-gateway
        PORT: 4000
        PORT_2: 4002
    environment:
      <<: *server-env
      SERVICE: api-gateway
    ports:
      - "4000:4000"
      - "4002:4002"
    depends_on:
      - user-service
    networks:
      - app-network

  # ─── Frontend ───
  client:
    build:
      context: ./packages/client
      dockerfile: Dockerfile
      args:
       PORT: 3001
       NEXT_PUBLIC_API_BASE_URL: http://a9cd3e083c24b4bdbbf01fa99bfa1dd5-110987320.ap-south-1.elb.amazonaws.com
    ports:
      - "3001:3001"
    depends_on:
      - api-gateway
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local