apiVersion: v1
kind: Service
metadata:
  name: api-gateway-lb
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - name: http-main
      port: 80
      targetPort: 4000
    - name: http-alt
      port: 81
      targetPort: 4002
