apiVersion: v1
kind: Service
metadata:
  name: app-gateway
  labels:
    app: app-gateway
    io.kompose.service: app-gateway
spec:
  selector:
    app: app-gateway
  ports:
    - name: http
      port: 4001
      targetPort: 4001
