apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: app-gateway
  name: app-gateway
spec:
  replicas: 5
  selector:
    matchLabels:
      io.kompose.service: app-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: app-gateway
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGINS
              value: http://localhost:3002
            - name: API_GATEWAY_HOST
              value: api-gateway
            - name: API_GATEWAY_PORT
              value: "4000"
            - name: API_GATEWAY_PORT_2
              value: "4002"
            - name: APP_GATEWAY_HOST
              value: app-gateway
            - name: APP_GATEWAY_PORT
              value: "4001"
            - name: CLIENT_URL
              value: http://localhost:3001
            - name: MONGO_URI
              value: mongodb://root:example@mongodb:27017/
            - name: SERVICE
              value: app-gateway
            - name: USER_SERVICE_HOST
              value: user-service
            - name: USER_SERVICE_PORT
              value: "4003"
            - name: USER_SERVICE_REDIS_HOST
              value: redis
            - name: USER_SERVICE_REDIS_PORT
              value: "6379"
          image: amancodes0/userlist-fullstack-hld-app-gateway
          name: app-gateway
          ports:
            - containerPort: 4001
              protocol: TCP
      restartPolicy: Always
