apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: app-gateway
  name: app-gateway
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
  selector:
    io.kompose.service: app-gateway
