apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
    io.kompose.service: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        io.kompose.service: user-service
    spec:
      containers:
        - name: user-service
          image: amancodes0/userlist-fullstack-hld-user-service
          ports:
            - containerPort: 4003
              protocol: TCP
          env:
            - name: ALLOWED_ORIGINS
              value: http://localhost:3002
            - name: API_GATEWAY_HOST
              value: 'api-gateway'
            - name: API_GATEWAY_PORT
              value: "4000"
            - name: API_GATEWAY_PORT_2
              value: "4002"
            - name: APP_GATEWAY_PORT
              value: "4001"
            - name: CLIENT_URL
              value: http://a7a29bab3405841518b42d403a6ace1b-1831602282.ap-south-1.elb.amazonaws.com
            - name: MONGO_URI
              value: mongodb://root:example@mongodb:27017/
            - name: SERVICE
              value: user-service
            - name: USER_SERVICE_PORT
              value: "4003"
            - name: USER_SERVICE_REDIS_HOST
              value: redis
            - name: USER_SERVICE_REDIS_PORT
              value: "6379"
      restartPolicy: Always
