apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
    io.kompose.service: user-service
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 4003
      targetPort: 4003
