apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: user-service
